### ISSUE TITLE
Code editor doesn't update rendering when backspace is pressed

### ISSUE THREAD

**Issue by ygra** [fskpf/svg2roughjs#43]

**Comment by fskpf** [comment]
Part of the commit is for #32. However, the `change` <-> `inputRead` is still a problem, because of triggering an unnecessary drawing when loading a file. The code-mirror states that `inputRead` should be user input changes. Sucks that backspace doesn't trigger it.

I think `keyup` should work best here.

**Comment by ygra** [comment]
Ah, sorry for that, then. `inputRead` is strictly for text input, i.e. a key that produces a character (or IME input). So backspace, since it has no character, doesn't trigger it, annoyingly.
